algoritmo "semnome"
// Função :
// Autor :
// Data : 25/03/2017
// Seção de Declarações 
var
cent, mil, metro, deci : real

inicio
escreva ("medida em centímetros: ")
leia (cent)
mil <- cent * 10
escreval ("Esta medida em milímetros é: ", mil ," milímetros")
metro <- cent / 100
escreval ("Esta medida em metros é:", metro ," metros")
deci <- cent / 10
escreva ("Esta medida em decímetros é:", deci ," decímetros")


// Seção de Comandos 
fimalgoritmo
