algoritmo "semnome"
// Função :
// Autor :
// Data : 22/08/2018
// Seção de Declarações 
var
  deposito : real
inicio
      deposito <- 500
               escreval("Primeiro mes R$", deposito)
               deposito <- (0.01 * deposito) + deposito
               escreval("Segundo mes R$", deposito)
               deposito <- (0.01 * deposito) + deposito
               escreval("terceiro mes R$", deposito)
               deposito <- (0.01 * deposito) + deposito
               escreval("quarto mes R$", deposito)


fimalgoritmo
