algoritmo "semnome"
// Função :
// Autor :
// Data : 22/08/2018
// Seção de Declarações 
var
anonasc, idade, idadefut, anoatual : real

inicio
escreva("Digite o seu ano de nascimento ")
leia(anonasc)
escreva("Digite o ano atual ")
leia(anoatual)
idade <- anoatual - anonasc
idadefut <- 2050 - anonasc
escreval("Sua idade é: ",idade)
escreva("Em 2050 você terá ", idadefut, " anos")
// Seção de Comandos 
fimalgoritmo
