algoritmo "semnome"
// Função :
// Autor :
// Data : 22/08/2018
// Seção de Declarações 
var
n1, n2, n3, n4, media : real
nome : caractere
inicio
escreva("Digite seu nome: ")
leia(nome)
escreva ("Digite a primeira nota: ")
leia(n1)
escreva ("Digite a segunda nota: ")
leia(n2)
escreva ("Digite a terceira nota: ")
leia(n3)
escreva ("Digite a quarta nota: ")
leia(n4)
media <- (n1 + n2 + n3 + n4) / 4
escreval ("Seu nome é: ", nome)
escreva ("Sua média é igual a: ", media)

// Seção de Comandos 
fimalgoritmo
